version: "3.7"

services:
  web:
    image: di-front-dev
    build:
      context: ./web
      dockerfile: prod.Dockerfile
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 3000:80
    container_name: di-front-dev
    depends_on:
      - server
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - web
  server:
    image: di-back-dev
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 5000:5000
    container_name: di-back-dev
