name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, cicd]
    types: [opened, synchronize]

jobs:
  server_deployment_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
