name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, cicd]
    types: [opened, synchronize]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DB_URI_TEST: ${{ secrets.DB_URI_TEST }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
jobs:
  server_deployment_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: test
        run: npm test
      - name: flyio deployment
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip')}}
        run: flyctl deploy --remote-only
